require("items.apple")
require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.widgets")
require("items.reminder")
-- require("items.weather")
-- require("items.spotify")
