#!/usr/bin/env zsh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"

MAIN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:' | awk '/Display Type/ {print $3}')

JETBRAINS_FONT_FACE="JetBrainsMono Nerd Font"
# FONT_FACE="JetBrainsMono Nerd Font"
FONT_FACE="SF Pro"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
  height=32 \
  color=0xff18191d \
  margin=0 \
  sticky=on \
  padding_left=8 \
  padding_right=8 \
  notch_width=188 \
  display=main

sketchybar --default \
  background.color=0xff23262f \
  background.corner_radius=5 \
  background.padding_right=5 \
  background.height=26 \
  icon.font="$FONT_FACE:Medium:15.0" \
  icon.padding_left=5 \
  icon.padding_right=5 \
  label.font="$FONT_FACE:Medium:12.0" \
  label.color=0xfffcfcfd \
  label.y_offset=0 \
  label.padding_left=0 \
  label.padding_right=5

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

sketchybar --add item front_app left \
  --set front_app \
  background.color=0xffa6da95 \
  background.padding_left=0 \
  background.padding_right=0 \
  icon.y_offset=1 \
  icon.color=0xff24273a \
  label.drawing=no \
  script="$PLUGIN_DIR/front_app.sh" \
  --add item front_app.separator left \
  --set front_app.separator \
  background.color=0x00000000 \
  background.padding_left=-3 \
  icon= \
  icon.color=0xffa6da95 \
  icon.font="$FONT_FACE:Bold:20.0" \
  icon.padding_left=0 \
  icon.padding_right=0 \
  icon.y_offset=1 \
  label.drawing=no \
  --add item front_app.name left \
  --set front_app.name \
  background.color=0x00000000 \
  background.padding_right=0 \
  icon.drawing=off \
  label.font="$FONT_FACE:Bold:12.0" \
  label.drawing=yes

sketchybar --add bracket front_app_bracket \
  front_app \
  front_app.separator \
  front_app.name
--subscribe front_app front_app_switched

# Center items
sketchybar --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify e \
  --set spotify \
  icon= \
  icon.y_offset=1 \
  icon.font="$JETBRAINS_FONT_FACE:Bold:20.0" \
  label.drawing=off \
  label.padding_left=3 \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify spotify_change mouse.clicked

sketchybar --add item weather q \
  --set weather \
  icon= \
  icon.color=0xfff5bde6 \
  icon.font="$FONT_FACE:Bold:15.0" \
  update_freq=1800 \
  script="$PLUGIN_DIR/weather.sh" \
  --subscribe weather system_woke

# Right items
sketchybar --add item clock right \
  --set clock \
  icon=󰃰 \
  icon.color=0xffed8796 \
  update_freq=10 \
  script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right \
  --set battery \
  update_freq=20 \
  script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
  --set volume \
  icon.color=0xff8aadf4 \
  label.drawing=true \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

# Finalizing setup
sketchybar --update
sketchybar --trigger space_change
