#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# defaults
yabai -m config layout bsp

yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 10
yabai -m config external_bar all:32:0

yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config focus_follows_mouse autoraise

yabai -m config auto_balance off
yabai -m config split_ratio 0.50
yabai -m config window_shadow float
yabai -m config window_placement second_child
yabai -m config insert_feedback_color 0xff9dd274

# apps spaces
yabai -m rule --add app="^Visual Studio Code$" space=^1
yabai -m rule --add app="^Arc$" space=^1
yabai -m rule --add app="^Things3$" space=^1
yabai -m rule --add app="^Figma$" space=2
yabai -m rule --add app="^Slack$" space=2
yabai -m rule --add app="^Spark Desktop$" space=3
yabai -m rule --add app="^Discord$" space=3
yabai -m rule --add app="^Messenger$" space=4
yabai -m rule --add app="^Spotify$" space=4

# disable apps
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Upwork$" manage=off
yabai -m rule --add app="^Pearcleaner$" manage=off
yabai -m rule --add app="^Dota 2$" manage=off
yabai -m rule --add app="^Obsidian$" manage=off
yabai -m rule --add app="^ChatGPT$" manage=off
yabai -m rule --add app="^Raindrop.io$" manage=off
yabai -m rule --add app="^Hoppscotch$" manage=off
yabai -m rule --add app="^Rakuten Viber$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^Permute 3$" manage=off
yabai -m rule --add app="^OrbStack$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add label="WhatsApp" app="WhatsApp" manage=off

# jankyborders
borders active_color=0xffa6da95 inactive_color=0xff494d64 width=2.0 blacklist="Calculator, Software Update,Dictionary,System Preferences,System Settings,zoom.us,Photo Booth,Archive Utility,App Store,Alfred,Activity Monitor,Safari,Finder,System Information,1Password,Upwork,Pearcleaner,Dota 2,Obsidian,ChatGPT,Hoppscotch,Rakuten Viber,Notes,Permute 3,OrbStack,iTerm2,WhatsApp" &

echo "yabai configuration loaded.."
