#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# defaults
yabai -m config layout                     bsp            \
                                                          \
                top_padding                8              \
                bottom_padding             8              \
                left_padding               8              \
                right_padding              8              \
                window_gap                 10             \
                external_bar               all:32:0       \
                                                          \
                mouse_follows_focus        on             \
                mouse_modifier             alt            \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                focus_follows_mouse        autoraise      \
                                                          \
                auto_balance               off            \
                split_ratio                0.50           \
                window_shadow              float          \
                window_placement           second_child   \
                insert_feedback_color      0xff9dd274     \
                
# apps spaces
yabai -m rule --add app="^Visual Studio Code$" space=^1
yabai -m rule --add app="^Arc$" space=^1
yabai -m rule --add app="^Things3$" space=^1
yabai -m rule --add app="^iTerm$" space=^1
yabai -m rule --add app="^Figma$" space=2
yabai -m rule --add app="^Slack$" space=2
yabai -m rule --add app="^Messenger$" space=3
yabai -m rule --add app="^Spotify$" space=3

# disable apps
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# jankyborders
borders active_color=0xffa6da95 inactive_color=0xff494d64 width=2.0 &

echo "yabai configuration loaded.."
