/**
 * `MachineFacts` to bridge markdown. Pure, so a test can assert the prose that a
 * given machine produces without probing one.
 *
 * Prose that no probe can settle (policy, procedure, pi's own tool surface) is
 * authored here verbatim. Everything else is interpolated or gated on a fact.
 */

import type { MachineFacts, ShimFact } from "./bridge-facts";

const WIDTH = 100;

function list(items: string[]): string {
	if (items.length <= 1) return items[0] ?? "";
	if (items.length === 2) return `${items[0]} and ${items[1]}`;
	return `${items.slice(0, -1).join(", ")}, and ${items.at(-1)}`;
}

/**
 * Interpolated facts change sentence length, so every generated sentence is
 * written as one long line and wrapped here. Authored prose is hand-wrapped and
 * never passed through this, because re-flowing it would fight its own layout.
 */
function wrap(paragraph: string): string {
	if (paragraph.length <= WIDTH) return paragraph;
	const indent = /^(\s*(?:- )?)/.exec(paragraph)![1].replace("- ", "  ");
	const out: string[] = [];
	let current = "";
	for (const word of paragraph.split(" ")) {
		const candidate = current ? `${current} ${word}` : word;
		if (candidate.length > WIDTH && current) {
			out.push(current);
			current = indent + word;
			continue;
		}
		current = candidate;
	}
	out.push(current);
	return out.join("\n");
}

function header(facts: MachineFacts): string {
	const version = facts.pstack.version ? ` ${facts.pstack.version}` : "";
	return `# pstack bridge

<!-- Generated by \`pstack-bridge\`. Edit \`~/.config/pi/agent/pstack-bridge/\`, not this file. -->

${wrap(`pstack was a Cursor plugin. This machine runs pi, paseo, and Anthropic models through cliproxyapi, against @zenspc/pi-pstack${version}. Read this file before running any pstack playbook. Where it contradicts a playbook, this file wins.`)}`;
}

const MISSING_TOOLS = `## Tools the playbooks name that pi does not have

**\`ask_user_question\`.** No such tool exists here. Where a playbook forbids it, that means do not stop
and ask. Where a playbook sanctions a question, write the question in the reply and stop.

**A todolist.** pi has no todo tool. "Open a todolist" means write a plan file at
\`\${PI_SESSION_FILE%.jsonl}.plan.md\`. One \`- [ ]\` box per playbook step, copied verbatim, before any
task-specific box. Tick a box only when its evidence exists. A skipped step keeps its box with
\`skip: <reason>\`. A file beats a TUI list because delegates can read it by absolute path.

**Cursor's Task tool.** Named by \`interrogate\` and \`orchestrate\`. Use \`subagent({ agent, task })\` from
pi-subagents. Model slugs come from the role table the pstack extension injects.`;

function delegation(facts: MachineFacts): string {
	const byName = new Map(facts.agents.map((agent) => [agent.name, agent]));
	const blocks = ["## Delegation"];

	const poteto = byName.get("poteto-agent");
	if (poteto) {
		blocks.push(
			`\`poteto-agent\` holds ${list(poteto.tools)}. It has no \`subagent\` tool, no web search, and no MCP access. Fan-out, web research, and every paseo call stay with the parent. Never write a brief that tells a delegate to spawn its own children.`,
		);
	}

	const sicko = byName.get("comment-sicko");
	if (sicko) {
		blocks.push(`\`comment-sicko\` holds ${list(sicko.tools)}, so it cannot write. It reports, the parent deletes.`);
	}

	if (!poteto && !sicko) {
		blocks.push("No pstack subagents are installed. Every playbook step that delegates runs in this session instead.");
	}
	return blocks.map(wrap).join("\n\n");
}

/** Named in the prose below, so a paseo rename fails the check instead of misleading a run. */
const PASEO_TOOLS = [
	"create_workspace",
	"create_agent",
	"send_agent_prompt",
	"get_agent_status",
	"get_agent_activity",
	"list_pending_permissions",
	"respond_to_permission",
	"create_schedule",
	"create_heartbeat",
	"list_schedules",
	"inspect_schedule",
	"schedule_logs",
];

function paseo(facts: MachineFacts): string {
	const server = facts.mcp.find((entry) => entry.name === "paseo" && entry.state !== "disabled");
	if (!server) {
		return `## Cloud agents have no backend here

Playbooks that say "Cursor cloud agent" have nothing to map onto, because no paseo MCP server is
reachable. Run that work in this session, or tell the user the step needs a long-lived agent it
cannot get. Local \`subagent()\` still covers read-only fan-out, which is \`how\`, \`why\`, \`arena\`,
\`swarm\`, \`interrogate\`, and \`reflect\`.`;
	}

	const missing = PASEO_TOOLS.filter((tool) => !server.tools.includes(tool));
	const renamed = missing.length
		? `\n\n${wrap(`${list(missing.map((tool) => `\`paseo_${tool}\``))} ${missing.length === 1 ? "is" : "are"} named here but absent from the server's tool list. Treat the step that needs one as blocked, and find its replacement rather than improvising a call.`)}`
		: "";
	const ambient =
		server.state === "ambient"
			? `\n\n${wrap("Nothing in `~/.config/mcp/mcp.json` declares paseo. The Paseo desktop app injects it at launch, so a pi started from a plain terminal has no paseo tools and every step in this section is unavailable there.")}`
			: "";

	return `## Cloud agents are paseo agents

Playbooks that say "Cursor cloud agent" mean a long-lived agent with its own checkout. Shipping step 1,
autopilot-full step 2, autopilot-stack step 1, and orchestrate all say it. Use the \`paseo\` MCP server.${ambient}

- \`paseo_create_workspace\` for the isolated checkout, one per PR owner.
- \`paseo_create_agent\`, then \`paseo_send_agent_prompt\` to deliver the brief.
- \`paseo_get_agent_status\` and \`paseo_get_agent_activity\` to probe read-only. Never resume an agent
  just to check on it, because a resume restarts an idle agent.
- \`paseo_list_pending_permissions\` and \`paseo_respond_to_permission\` when an owner blocks.

Local \`subagent()\` still covers read-only fan-out inside one session, which is \`how\`, \`why\`, \`arena\`,
\`swarm\`, \`interrogate\`, and \`reflect\`. Reach for paseo when the work outlives this session or needs its
own working tree.

Orchestrate's Cursor-restart rule maps to a pi restart. Local subagents die, paseo agents do not.
Reattach by PR and branch, never by agent id.${renamed}

## Automations are paseo schedules

The benny pack never ported. \`automate-me\` targets \`paseo_create_schedule\` for recurring agent runs and
\`paseo_create_heartbeat\` for recurring nudges. Inspect with \`paseo_list_schedules\`,
\`paseo_inspect_schedule\`, and \`paseo_schedule_logs\`.`;
}

function forge(facts: MachineFacts): string {
	const { gh, user, origin, graphite } = facts.forge;
	const sentences: string[] = [];

	if (gh) sentences.push(`\`gh\` is the forge${user ? `, authenticated as \`${user}\`` : ", with no account in `~/.config/gh/hosts.yml`"}.`);
	else sentences.push("No `gh` on PATH. Every playbook step that reads or writes a PR is blocked until one is installed.");

	if (origin) sentences.push(`The \`origin\` CLI is installed at \`${origin}\`, so its playbook branches apply.`);
	else sentences.push("The `origin` CLI is not installed, so skip every Origin branch in shipping, babysit, autopilot, and opening-a-pr.");

	sentences.push(graphite ? `Graphite is installed at \`${graphite}\`.` : "Graphite is not used either.");

	return `## Forge\n\n${wrap(sentences.join(" "))}`;
}

function shimLine(shim: ShimFact): string {
	const name = shim.argument ? `\`${shim.name} ${shim.argument}\`` : `\`${shim.name}\``;
	if (!shim.path) return `- ${name} is MISSING from PATH, so ${shim.playbooks} cannot run the step that needs it.`;
	if (!shim.targetExists) return `- ${name} is on PATH but execs \`${shim.target}\`, which no longer exists. The ${shim.playbooks} step is broken.`;
	return `- ${name} replaces \`${shim.replaces}\` in ${shim.playbooks}.`;
}

function scripts(facts: MachineFacts): string {
	const present = facts.shims.filter((shim) => shim.path);
	const dirs = [...new Set(present.map((shim) => shim.path!.replace(/\/[^/]+$/, "")))];
	const where =
		present.length === 0
			? "None of them are on PATH right now, so every step below is blocked rather than optional."
			: `The ${present.length} on PATH run from ${list(dirs.map((dir) => `\`${dir}\``))}.`;
	const runtime = facts.bun
		? `\`watch-pr\` and \`orch\` run under bun, which lives at \`${facts.bun}\`.`
		: "bun is not installed, so `watch-pr` and `orch` will not start.";

	return `## Bundled scripts

${wrap(`The playbooks name these by relative path, which never resolves from a project directory. Use the PATH shims instead. ${where}`)}

${facts.shims.map(shimLine).map(wrap).join("\n")}

${wrap(runtime)}`;
}

const REVIEW = `## Review automation is local, not Bugbot

Cursor Bugbot is not installed and will not be. Never wait for a bot review, and never treat a missing
bot as a blocked step.

Wherever a playbook names Bugbot triage, run the review yourself instead. Babysit step 8,
autopilot-full step 2, and autopilot-stack step 1 all name it.

1. Scope the diff against the PR base, not the working tree.
2. Run the \`interrogate\` skill over that diff. Its reviewers come from the \`interrogate reviewers\`
   role list, so the adversarial signal is model diversity. For a small or docs-only PR, one
   fresh-context \`reviewer\` subagent is enough.
3. Triage every finding through \`poteto-mode/references/bugbot-triage.md\` unchanged. The rubric is
   about noisy machine review in general, so \`fix\`, \`dismiss\`, and \`ask\` still apply.
4. Record each dismissal with its concrete disproof in the run report. There is no thread to reply to,
   so the report is the only record.

The pass-count escalation in babysit step 8 has no meaning here, because you control how many reviews
run. Stop when a pass produces no new \`fix\` findings.

If some other bot does comment on a PR, such as Copilot or a repo's own workflow, triage it with the
same rubric and the same skeptical posture.`;

function browser(facts: MachineFacts): string {
	const playwright = facts.mcp.find((server) => server.name === "playwright");
	const mcpNote =
		playwright?.state === "enabled" || playwright?.state === "ambient"
			? "\nThe `playwright` MCP server is currently reachable, against the standing instruction to keep it\ndisabled in `~/.config/mcp/mcp.json`. Disable it rather than calling it."
			: playwright?.state === "disabled"
				? "\nThe `playwright` MCP server is disabled in `~/.config/mcp/mcp.json`; do not re-enable it."
				: "";

	return `## Verifying on a real surface

Drive browsers through the \`playwright-cli\` skill with \`--browser=firefox\`. Never Chrome or Chromium
without asking.${mcpNote}
To show the user a page, run \`open "<url>"\` instead of automating a browser.`;
}

function skills(facts: MachineFacts): string {
	const { root, discoverable, hidden } = facts.pstack;
	if (!root) {
		return `## pstack is not installed

No \`@zenspc/pi-pstack\` package is present. Every skill a playbook names is unavailable, so say so
rather than improvising a substitute.`;
	}

	const shadowed = facts.sharedSkills.shadowed;
	const shadowNote = shadowed.length
		? `\n\n${wrap(`${list(shadowed.map((name) => `\`${name}\``))} ${shadowed.length === 1 ? "exists" : "exist"} twice, in the package and under \`${facts.sharedSkills.root}/\`. Discovery keeps the shared copy, which is the one \`AGENTS.md\` names, so \`/skill:<name>\` and that path agree. The packaged copy is shadowed.`)}`
		: "";

	return `## Skills the system prompt does not list

${wrap(`${hidden.length} of the ${hidden.length + discoverable.length} pstack skills set \`disable-model-invocation: true\`, so they never appear in the available-skills list even though they are installed. A name missing from that list is not a missing skill. Invoke one as \`/skill:<name>\`, or read it by absolute path when a delegate brief needs it, because a delegate cannot run a slash command.`)}
They live at \`${root}/skills/<name>/SKILL.md\`.
${wrap(`The ${discoverable.length} that do appear are ${list(discoverable.map((name) => `\`${name}\``))}.`)}

\`deslop\` is the one the playbooks name most, and it is installed at
\`${root}/skills/deslop/SKILL.md\`.
Two corrections for this machine:

- It scopes itself to "the diff against main" and to slop "introduced in the branch". Work here sits
  uncommitted on \`main\`, so scope it to the working tree instead: \`git diff\` plus the untracked files
  in \`git status --short\`. Never \`git diff main\`, which is empty here.
- It owns code slop, meaning stray comments, defensive branches, \`any\` casts, and needless nesting.
  \`unslop\` owns prose. A step naming both wants both, run over the same diff.${shadowNote}`;
}

function playbooks(facts: MachineFacts): string {
	if (facts.playbooks.length === 0) return "";

	const entries = facts.playbooks.map((playbook) => {
		const outranks = playbook.outranks ? ` It outranks ${playbook.outranks}.` : "";
		const command = playbook.command ? ` \`${playbook.command}\` runs it directly.` : "";
		return wrap(`- **${playbook.name}.** ${playbook.description} \`${playbook.path}\`.${outranks}${command}`);
	});

	return `## Local playbooks the skill list does not name

poteto-mode's playbook list ships inside the npm package and an update overwrites it. Local playbooks
live in \`~/.pi/agent/pstack/playbooks/\` instead and are registered here. Match them the same way, and
prefer the local one when both fit.

Match this list before the bundled one, not after. poteto-mode's Playbooks section cannot name these, so
a task that fits one here would otherwise fall through to a bundled playbook or to figure-it-out, which
is the wrong answer rather than a near miss.

${entries.join("\n")}`;
}

const GIT_AUTHORITY = `## Git authority beats every playbook

\`~/.pi/agent/AGENTS.md\` wins. A playbook runs until the diff is ready to review, then stops. Do not
stage, commit, push, open a PR, or merge without an explicit instruction, and \`/ship\` is that
instruction. So \`playbooks/opening-a-pr.md\` is not an automatic ending, and shipping, autopilot-full,
and autopilot-stack are programs the user names, never defaults.`;

export function renderBridge(facts: MachineFacts): string {
	const sections = [
		header(facts),
		MISSING_TOOLS,
		delegation(facts),
		paseo(facts),
		forge(facts),
		scripts(facts),
		REVIEW,
		browser(facts),
		skills(facts),
		playbooks(facts),
		GIT_AUTHORITY,
	];
	return `${sections.filter(Boolean).join("\n\n")}\n`;
}
